["protostar.config"]
protostar_version = "0.6.0"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
DefiPooling = [
    "./contracts/DefiPooling.cairo"
]
token_bridge = [
    "./contracts/token_bridge.cairo",
]